import "../styles/global.css";
import GlassPane from "@/components/GlassPane";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const header = (
  <header>
    <div className=" w-full text-center bg-slate-800 p-8">
      <Image
        src="/logo.png"
        width={40}
        height={40}
        className="mx-auto"
        alt={"logo"}
      />
      <Link href="/">
        <h1 className="text-2xl text-white font-bold mt-4">Bittensor.org</h1>
      </Link>
      <p className="text-slate-300"> Incentivizing Intelligence. </p>
    </div>
  </header>
);

const footer = (
  <footer>
    <div className="border-t border-slate-400 mt-12 py-6 text-center text-slate-400">
      <h3>This site is build by the team behind bittensor.org</h3>
    </div>
  </footer>
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full">
          {header}
          <div className="max-w-6xl px-6 mx-auto">
            {children}
            {footer}
          </div>
      </body>
    </html>
  )
}
